apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kube-events
  namespace: kube-events
spec:
  type: bindings.kubernetes
  version: v1
  metadata:
  - name: namespace
    value: kube-events
  - name: resyncPreiodInSec
    value: "5"