apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: a
spec:
  consumerGroup: knative-group
  bootstrapServers:
    - my-cluster-kafka-bootstrap.kafka:9092 # note the kafka namespace
  topics:
    - topic-a
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display-a
