apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: native
spec:
  type: exporters.native
  version: v1
  metadata:
  - name: enabled
    value: "true"
  - name: agentEndpoint
    value: "ai-local-forwarder:55678"