apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: topic-b
spec:
  type: bindings.kafka
  version: v1
  metadata:
    # Kafka broker connection setting
    - name: brokers
      value: my-cluster-kafka-bootstrap.kafka:9092
    # consumer configuration: topic and consumer group
    - name: topics
      value: sample
    - name: consumerGroup
      value: group1
    # publisher configuration: topic
    - name: publishTopic
      value: topic-b
    - name: authRequired
      value: "false"
