apiVersion: v1
kind: Secret
metadata:
  name: demo-twitter-secret
type: Opaque
data:
  consumerKey: {{ .Values.twitter.consumerKey | b64enc }}
  consumerSecret: {{ .Values.twitter.consumerSecret | b64enc }}
  accessToken: {{ .Values.twitter.accessToken | b64enc }}
  accessSecret: {{ .Values.twitter.accessSecret | b64enc }}