apiVersion: v1
kind: Secret
metadata:
  name: demo-processor-secret
type: Opaque
data:
  token: {{ .Values.cognitiveService.token | b64enc }}
  endpoint: {{ .Values.cognitiveService.endpoint | b64enc }}