apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider
  labels:
    app: provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
        demo: {{ .Values.demoName }}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "provider"
        dapr.io/app-port: {{ .Values.provider.port | quote }}
        dapr.io/log-as-json: "true"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: provider
        image: {{ .Values.provider.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.provider.port }}
        env:
        - name: PORT
          value: {{ .Values.provider.port | quote }}
        - name: DAPR_HTTP_PORT
          value: {{ .Values.dapr.port | quote}}
