apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: public.ecr.aws/diagrid/conductor-charts
    chart: agent
    targetRevision: 0.349.0
    helm:
      values: |
        agent:
          extraArgs: null
          goMemLimit: 600MiB
          image: >-
            us-central1-docker.pkg.dev/prj-common-p-shared-79896/reg-p-common-docker-public/agent:0.349.0
          installDependencies: false
          key: >-
            agentkey||gcp||projects/199538153898/secrets/b3d3be8b-73e1-48af-ae5c-98065a203371/versions/1
          keyB64: NzQ5MzhhZGItYTAzNi00ZjJmLTk5ZDktYWJiMWU0NTEzNzc2
          logLevel: info
          nodeAffinity: null
          nodeSelector: null
          replicas: 2
          resources:
            limits:
              memory: 750Mi
            requests:
              cpu: 10m
              memory: 250Mi
          tlsEnabled: true
          tlsMutual: false
          tolerations: null
        appName: diagrid-agent
        caCertPEM: |
          -----BEGIN CERTIFICATE-----
          MIIE5zCCA8+gAwIBAgISA2c0PFimvtXEaui89XuigaKWMA0GCSqGSIb3DQEBCwUA
          MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
          EwNSMTEwHhcNMjUwMzA5MTQ1OTE0WhcNMjUwNjA3MTQ1OTEzWjAXMRUwEwYDVQQD
          DAwqLmRpYWdyaWQuaW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCv
          tOm1KHJwJ6X+AhCQAeikBsGncgvQt2P0bVHoqIDIvvyh1I7cOUKiOehxaRJqS5a2
          YwgfkA/XdrYaQ97yA16rhc+OoXnaAn/SkZWzFjaQJTlgWVPO2u5LOvh7RYkavopz
          b6k309tU5Xtyipj6czvIBlNclCtozI4jWq/RRYtVfOPJFleCq2gRDx0wpjqjTbXC
          QmUoRuUrr2XP4UOAru5tfxA/UdViJfhdazInWybSnXWNoVSaefqrxK6Dc+1S9Drx
          8u2+N3a8t24C60QRM22lZud96tjTWSatCTURrLAdfK239enlXyqnvxASnO5kkv1n
          PyyCGy72I1YAOqPAaLxJAgMBAAGjggIPMIICCzAOBgNVHQ8BAf8EBAMCBaAwHQYD
          VR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0O
          BBYEFMQzI8NTi1HkG76EhYMwm9EhJ2fnMB8GA1UdIwQYMBaAFMXPRqTq9MPAemyV
          xC2wXpIvJuO5MFcGCCsGAQUFBwEBBEswSTAiBggrBgEFBQcwAYYWaHR0cDovL3Ix
          MS5vLmxlbmNyLm9yZzAjBggrBgEFBQcwAoYXaHR0cDovL3IxMS5pLmxlbmNyLm9y
          Zy8wFwYDVR0RBBAwDoIMKi5kaWFncmlkLmlvMBMGA1UdIAQMMAowCAYGZ4EMAQIB
          MIIBAwYKKwYBBAHWeQIEAgSB9ASB8QDvAHUAzPsPaoVxCWX+lZtTzumyfCLphVwN
          l422qX5UwP5MDbAAAAGVe6BlxwAABAMARjBEAiAIlBap3no+0AtqBRoEfPY+bi7y
          G1hGE8Ko4iKDhUCbiwIgNzDCpKkCUJtsjXv4Sb+2iDoU2YLaHiaDxvZraLCIvywA
          dgDgkrP8DB3I52g2H95huZZNClJ4GYpy1nLEsE2lbW9UBAAAAZV7oGXlAAAEAwBH
          MEUCIBTXQnlvM0uGi9nlj5LQg0IH278pDy0Txe2GKUTxMnBlAiEAv6NVPlbjaP7j
          kucO9+B3jE4l9vVxRPliaAjFE0rrTZowDQYJKoZIhvcNAQELBQADggEBAEYX5c4p
          rp6Ipj1Q/wFG/PSpVOTfhGnkoeTVTJTkDC5SEZNhUu+qZuHabPkwQ2ETJq8iGKU/
          aN7S559J+qAmjzd9kVSD1K1vGmp0iBQURcAQcGyGKXUa6ixOBOdQOCZ3/+wjhgLP
          7lVVGKmpfIc28dUe+RPccRZ8xaONvNJ7IupLveR+20yEVhUxeg8/a+UDR9GOqexv
          yFfFiUT0fxdIKfgyihhY/CaWFaVXRCoLOwy4ynpqbChVHxULoKmGouGgkoh1wOmQ
          4n9mSPb8bYf2qPatyZTu9dhjBZ8sTH2ZJZuVQqQ2Lo1Kata7XJgtj8VaYY8IyE25
          APeFsWyNSsuOQdU=
          -----END CERTIFICATE-----
          -----BEGIN CERTIFICATE-----
          MIIFBjCCAu6gAwIBAgIRAIp9PhPWLzDvI4a9KQdrNPgwDQYJKoZIhvcNAQELBQAw
          TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
          cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjQwMzEzMDAwMDAw
          WhcNMjcwMzEyMjM1OTU5WjAzMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
          RW5jcnlwdDEMMAoGA1UEAxMDUjExMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
          CgKCAQEAuoe8XBsAOcvKCs3UZxD5ATylTqVhyybKUvsVAbe5KPUoHu0nsyQYOWcJ
          DAjs4DqwO3cOvfPlOVRBDE6uQdaZdN5R2+97/1i9qLcT9t4x1fJyyXJqC4N0lZxG
          AGQUmfOx2SLZzaiSqhwmej/+71gFewiVgdtxD4774zEJuwm+UE1fj5F2PVqdnoPy
          6cRms+EGZkNIGIBloDcYmpuEMpexsr3E+BUAnSeI++JjF5ZsmydnS8TbKF5pwnnw
          SVzgJFDhxLyhBax7QG0AtMJBP6dYuC/FXJuluwme8f7rsIU5/agK70XEeOtlKsLP
          Xzze41xNG/cLJyuqC0J3U095ah2H2QIDAQABo4H4MIH1MA4GA1UdDwEB/wQEAwIB
          hjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwEgYDVR0TAQH/BAgwBgEB
          /wIBADAdBgNVHQ4EFgQUxc9GpOr0w8B6bJXELbBeki8m47kwHwYDVR0jBBgwFoAU
          ebRZ5nu25eQBc4AIiMgaWPbpm24wMgYIKwYBBQUHAQEEJjAkMCIGCCsGAQUFBzAC
          hhZodHRwOi8veDEuaS5sZW5jci5vcmcvMBMGA1UdIAQMMAowCAYGZ4EMAQIBMCcG
          A1UdHwQgMB4wHKAaoBiGFmh0dHA6Ly94MS5jLmxlbmNyLm9yZy8wDQYJKoZIhvcN
          AQELBQADggIBAE7iiV0KAxyQOND1H/lxXPjDj7I3iHpvsCUf7b632IYGjukJhM1y
          v4Hz/MrPU0jtvfZpQtSlET41yBOykh0FX+ou1Nj4ScOt9ZmWnO8m2OG0JAtIIE38
          01S0qcYhyOE2G/93ZCkXufBL713qzXnQv5C/viOykNpKqUgxdKlEC+Hi9i2DcaR1
          e9KUwQUZRhy5j/PEdEglKg3l9dtD4tuTm7kZtB8v32oOjzHTYw+7KdzdZiw/sBtn
          UfhBPORNuay4pJxmY/WrhSMdzFO2q3Gu3MUBcdo27goYKjL9CTF8j/Zz55yctUoV
          aneCWs/ajUX+HypkBTA+c8LGDLnWO2NKq0YD/pnARkAnYGPfUDoHR9gVSp/qRx+Z
          WghiDLZsMwhN1zjtSC0uBWiugF3vTNzYIEFfaPG7Ws3jDrAMMYebQ95JQ+HIBD/R
          PBuHRTBpqKlyDnkSHDHYPiNX3adPoPAcgdF3H2/W0rmoswMWgTlLn1Wu0mrks7/q
          pdWfS6PJ1jty80r2VKsM/Dj3YIDfbjXKdaFU5C+8bhfJGqU3taKauuz0wHVGT3eo
          6FlWkWYtbt4pgdamlwVeZEW+LM7qZEJEsMNPrfC03APKmZsJgpWCDWOKZvkZcvjV
          uYkQ4omYCTX5ohy+knMjdOmdH9c7SpqEWBDC86fiNex+O0XOMEZSa8DA
          -----END CERTIFICATE-----
        clientCertPEM: ''
        clientKeyPEM: ''
        dapr:
          enabled: true
        daprRbacTargetServiceAccountName: diagrid-agent
        global:
          agentId: 104c4c37-cae5-4963-8fd8-54d83ab48ede
          cloudUrl: cloudgrid.diagrid.io:443
          customCA: ''
          isLocal: false
          isOpenShift: false
          kubernetesOs: linux
          mainServiceAccountName: diagrid-agent
          manifestId: 1.0.199
          namespace: diagrid-cloud
          namespaceDefault: diagrid-cloud
          orgId: 3b18f4de-dc32-4bad-a669-4bbfb75a5ed0
          proxyConfig: null
          sccTargetServiceAccountName: diagrid-agent-logs-collector
        isUseElevatedPermissions: false
        labels: {}
        mainClusterRoleBindingName: diagrid
        mainClusterRoleName: diagrid
        manifestApiVersion: diagrid.io/v1beta1
        manifestKind: Manifest
        otelLogsCollector:
          daprLogsURL: cloudgrid.diagrid.io:443
          enabled: true
          goMemLimit: 600MiB
          image: >-
            us-central1-docker.pkg.dev/prj-common-p-shared-79896/reg-p-common-docker-public/diagrid-otel-collector:0.349.0
          isLogsLimited: false
          labels: {}
          logLevel: info
          nodeAffinity: null
          nodeSelector: null
          remoteWriteAuthEnabled: true
          remoteWriteTlsInsecure: false
          remoteWriteURL: https://metrics.diagrid.io/api/v1/push
          resources:
            limits:
              memory: 750Mi
            requests:
              cpu: 10m
              memory: 125Mi
          tlsEnabled: true
          tlsInsecure: false
          tolerations: null
        otelMetricsCollector:
          enabled: true
          goMemLimit: 1638MiB
          image: >-
            us-central1-docker.pkg.dev/prj-common-p-shared-79896/reg-p-common-docker-public/diagrid-otel-collector:0.349.0
          labels: {}
          logLevel: info
          nodeAffinity: null
          nodeSelector: null
          remoteWriteAuthEnabled: true
          remoteWriteTlsInsecure: false
          remoteWriteURL: https://metrics.diagrid.io/api/v1/push
          replicas: 2
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 250Mi
          tlsEnabled: true
          tolerations: null
        sccName: diagrid-agent

  destination:
    server: https://kubernetes.default.svc
    namespace: dapr-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # Add the ignoreDifferences section here
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: subscriptions.dapr.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/service/namespace
        - /spec/conversion/webhook/clientConfig/caBundle