apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: argocd-demo
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master.redis.svc.cluster.local:6379
  - name: redisPassword
    value: ""
  - name: enableTLS
    value: "false"