name: Twitter Demo

on:
  # Triggers the workflow on push
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # The name of the resource group to be created. All resources will be place
  # in the resource group and start with name.
  RG_NAME: "twitterDemo"

  # The location to store the meta data for the deployment.
  LOCATION: "eastus"

  #The version of the dapr runtime version to deploy.
  DAPR_VERSION: "1.0.0"

  # The version of k8s control plane.
  K8S_VERSION: "1.19.6"

jobs:
  provider:
    name: build provider image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [provider, processor, viewer]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: darquewarrior/${{ matrix.app }}:${{ github.run_number }}
          context: ./twitter-sentiment-processor/demos/demo2/${{ matrix.app }}/